version: '3.8'
services:
  wegonice-db:
    image: 'mongo:7'
    container_name: 'wegonice-db'
    env_file:
      - .env
    volumes:
      - /opt/wegonice-db/db-data:/data/db
    ports:
      - '27017-27019:27017-27019'
  wegonice-api:
    image: 'ghcr.io/pfmartin/wegonice-api:latest'
    container_name: 'wegonice-api'
    volumes:
      - ./.env:/app/.env
    ports:
      - '8000:8000'
