name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches: '*'
    tags: '*'

jobs:
  static-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prettier check
        run: npm run prettier:check

  set-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version
        run: ./set_app_version.sh
